## XGBoost

### What is **Ensemble Learning**?

Ensemble learning combines multiple models (called **weak learners**) to produce a more powerful **aggregate model**.
The idea is that **a group of weak models**, when combined correctly, can outperform a single strong model.

---

### **1. Bagging (Bootstrap Aggregating)**

### What is Bagging?

**Bagging** stands for **Bootstrap Aggregating**.
It is a technique where multiple models are trained on **different random subsets** of the training data (with replacement), and their predictions are **aggregated (averaged or voted)** to make the final prediction.

### Key Characteristics:

* Reduces **variance** (i.e., prevents overfitting).
* Each model is trained **independently**.
* Uses **bootstrapping** — sampling data **with replacement**.
* Final output is by **majority voting (classification)** or **averaging (regression)**.

### Example Algorithm:

* **Random Forest** is the most famous example of Bagging.

  * It builds many Decision Trees on random subsets of data and features.

### **2. Boosting**

### What is Boosting?

**Boosting** is an ensemble technique that builds models **sequentially**, where each model tries to **correct the mistakes** of the previous one.

### Key Characteristics:

* Reduces **bias** and also **variance**.
* Models are trained **one after another** (sequentially).
* Each new model focuses more on the **previous errors**.
* Final prediction is a **weighted sum** of individual models.

---

### How Boosting Works (Simplified):

1. Start with a weak model (e.g., a shallow decision tree).
2. Evaluate errors from the model.
3. Give **higher weight** to the wrongly predicted instances.
4. Train a new model that focuses more on those errors.
5. Combine all models using weighted voting or averaging.

---

### Types of Boosting Algorithms:

---

### 1. **AdaBoost (Adaptive Boosting)**

* First popular boosting algorithm.
* Assigns weights to training examples; misclassified ones get higher weights.
* Combines models by **weighted majority voting**.
* Sensitive to **noisy data**.

**Library**: `sklearn.ensemble.AdaBoostClassifier`

---

### 2. **Gradient Boosting (GBM)**

* Builds trees **sequentially**, where each new tree **tries to minimize the error** of the overall model using **gradient descent**.
* Slower than random forest but **very powerful**.

**Library**: `sklearn.ensemble.GradientBoostingClassifier`

---

### 3. **XGBoost (Extreme Gradient Boosting)**

* An optimized version of Gradient Boosting.
* **Faster** and more **efficient** (uses parallelization, regularization).
* Supports **early stopping**, **missing values**, etc.
* Widely used in **Kaggle competitions**.

**Library**: `xgboost.XGBClassifier`

---

### 4. **LightGBM (Light Gradient Boosting Machine)**

* Boosting algorithm designed for **speed and efficiency**.
* Uses **histogram-based algorithms** for fast training.
* Great for **large datasets**.

**Library**: `lightgbm.LGBMClassifier`

---

### 5. **CatBoost**

* Developed by Yandex.
* Handles **categorical features** natively.
* Easy to use and robust to overfitting.

**Library**: `catboost.CatBoostClassifier`

---

### Bagging vs Boosting (Comparison Table)

| Feature           | Bagging                                 | Boosting                       |
| ----------------- | --------------------------------------- | ------------------------------ |
| Training          | Parallel                                | Sequential                     |
| Goal              | Reduce variance                         | Reduce bias (and variance)     |
| Data Sampling     | Random with replacement (bootstrapping) | Re-weighted by previous errors |
| Model Dependency  | Independent models                      | Dependent models               |
| Risk              | Less overfitting                        | Can overfit if not tuned       |
| Example Algorithm | Random Forest                           | AdaBoost, XGBoost, LightGBM    |

---

### Summary

* **Bagging**: Improves stability and accuracy, best when base model is high variance (e.g., Decision Trees).
* **Boosting**: Improves performance by correcting errors of the previous models; more powerful but needs careful tuning.

### Importing the libraries

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importing the dataset

In [6]:
df = pd.read_csv('../../datasets/Data_Classification.csv')
print(df.sample(5))

     Sample code number  Clump Thickness  Uniformity of Cell Size  \
410             1258549                9                       10   
402             1239967                1                        1   
614             1225382                6                        2   
289              636130                1                        1   
330              822829                7                        6   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
410                        10                 10                           10   
402                         1                  1                            2   
614                         3                  1                            2   
289                         1                  1                            2   
330                         4                  8                           10   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
410           10             

In [7]:
X = df.iloc[:, 1:-1].values
y = df.iloc[:, -1].values
print(X)
print('\n')
print(y)

[[ 5  1  1 ...  3  1  1]
 [ 5  4  4 ...  3  2  1]
 [ 3  1  1 ...  3  1  1]
 ...
 [ 5 10 10 ...  8 10  2]
 [ 4  8  6 ... 10  6  1]
 [ 4  8  8 ... 10  4  1]]


[2 2 2 2 2 4 2 2 2 2 2 2 4 2 4 4 2 2 4 2 4 4 2 2 4 2 2 2 2 2 2 4 2 2 2 4 2
 4 4 4 4 4 4 2 4 2 2 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 2 4 2 4 4 2 2 4 2 4 4 2
 2 2 2 2 2 2 2 2 4 4 4 4 2 2 2 2 2 2 2 2 2 2 4 4 4 4 2 4 4 4 4 4 2 4 2 4 4
 4 2 2 2 4 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 4 2 2 4 2 4
 4 2 2 4 2 2 4 4 2 2 2 2 4 4 2 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 4 2 4 4 4 2 4
 4 2 2 2 2 2 2 2 2 4 4 2 2 2 4 4 2 2 2 4 4 2 4 4 4 2 2 4 2 2 4 4 4 4 2 4 4
 2 4 4 4 2 4 2 4 4 4 4 2 2 2 2 2 2 4 4 2 2 4 2 4 4 4 2 2 2 2 4 4 4 4 4 2 4
 4 4 2 4 2 4 4 2 2 2 2 4 2 2 4 4 4 4 4 2 4 4 2 2 4 4 2 2 4 4 2 4 2 4 4 2 2
 4 2 2 2 4 2 2 4 4 2 2 4 2 4 2 2 4 2 4 4 4 2 2 4 4 2 4 2 2 4 4 2 2 2 4 2 2
 2 4 4 2 2 2 4 2 2 4 4 4 4 4 4 2 2 2 2 4 4 2 2 2 2 2 2 2 2 2 2 2 2 2 4 2 2
 2 2 4 2 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 2 2 2 2 2 2 2 2 4 2 4 2 4 2 2 2 2 4
 2 2 2 4 2 4 2 2 

### Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(X_train)
print('\n')
print(X_test)
print('\n')
print(y_train)
print('\n')
print(y_test)

[[10  1  1 ...  5  4  1]
 [ 1  1  1 ...  3  1  1]
 [ 5  1  1 ...  3  1  1]
 ...
 [ 1  1  1 ...  1  1  1]
 [ 3  1  1 ...  2  1  1]
 [10  9  7 ...  7  7  1]]


[[ 1  1  1 ...  1  1  1]
 [ 3  1  1 ...  2  1  1]
 [ 5  5  5 ...  4  3  1]
 ...
 [ 4  1  1 ...  1  1  1]
 [ 4 10  4 ...  9 10  1]
 [ 2  1  1 ...  2  1  1]]


[4 2 2 2 4 2 2 2 2 4 2 4 2 4 4 2 2 2 2 4 4 2 4 4 4 4 4 4 2 2 2 2 2 2 4 4 4
 2 2 2 4 2 2 4 4 2 4 2 2 4 4 2 2 2 2 2 2 2 2 2 2 4 2 2 2 2 2 4 4 2 4 2 2 2
 4 2 2 2 2 4 4 2 2 4 4 2 2 4 4 2 4 2 4 4 2 2 2 4 2 4 2 4 2 2 2 2 2 4 2 2 4
 2 2 4 2 2 2 2 2 4 2 2 4 2 4 2 2 4 4 4 2 2 2 2 2 2 4 4 2 2 2 2 2 2 2 4 2 2
 4 2 2 2 2 2 2 2 4 2 2 2 4 4 2 4 2 2 2 4 2 2 2 4 4 2 4 2 2 4 2 2 2 2 2 2 2
 4 4 4 4 2 4 2 4 2 4 4 4 2 2 4 2 2 2 2 4 4 2 2 2 4 2 2 4 2 2 2 2 4 4 2 2 2
 2 2 2 2 2 2 2 2 4 2 4 2 2 2 2 2 2 4 4 4 4 2 2 4 2 4 2 4 2 2 2 2 4 2 4 2 2
 2 2 4 2 2 4 2 2 2 2 2 2 2 4 2 4 2 2 2 4 2 2 2 2 2 4 2 2 2 2 4 2 2 4 2 2 2
 2 4 4 2 2 2 2 4 2 2 4 2 2 2 2 4 4 2 4 2 4 2 2 2 4 4 4 2 2 2 2 2 2 2 2 4 4
 2 2 2 2 

### Training XGBoost on the Training set

In [11]:
from xgboost import XGBClassifier

y_train_mapped = (y_train == 4).astype(int)
y_test_mapped = (y_test == 4).astype(int)

classifier = XGBClassifier()
classifier.fit(X_train, y_train_mapped)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

### Making the Confusion Matrix

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, recall_score, precision_score

y_pred_original = classifier.predict(X_test)
y_pred = [4 if pred == 1 else 2 for pred in y_pred_original]
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
precision = precision_score(y_test, y_pred, average='macro')
print("Precision (macro):", precision)
recall = recall_score(y_test, y_pred, average='macro')
print("Recall (macro):", recall)
f1 = f1_score(y_test, y_pred, average='macro')
print("F1 Score (macro):", f1)

Confusion Matrix:
 [[85  2]
 [ 2 48]]
Accuracy: 0.9708029197080292
Precision (macro): 0.9685057471264368
Recall (macro): 0.9685057471264368
F1 Score (macro): 0.9685057471264368
