## DEEP LEARNING DAY - 1 : Artificial Neural Network

### What is Deep Learning?

**Deep Learning** is a subset of **Machine Learning (ML)** that uses **artificial neural networks** with many layers (hence “deep”) to automatically learn features and patterns from data.

#### Key Characteristics:

* Uses **neural networks** with multiple layers (input, hidden, output).
* Learns **complex patterns** directly from raw data (images, text, etc.).
* Requires **large datasets** and **high computational power** (GPUs/TPUs).
* Performs **automatic feature extraction** — no need for manual feature engineering.

---

### How is Deep Learning different from Machine Learning?

| Feature                          | Machine Learning (ML)                         | Deep Learning (DL)                                |
| -------------------------------- | --------------------------------------------- | ------------------------------------------------- |
| **Feature Engineering**          | Manual (human-defined features)               | Automatic (learned from raw data)                 |
| **Data Dependency**              | Works well with small to medium datasets      | Needs large datasets to perform well              |
| **Model Type**                   | Algorithms like SVM, Decision Tree, KNN, etc. | Multi-layer Neural Networks (ANN, CNN, RNN, etc.) |
| **Training Time**                | Faster                                        | Slower (depends on model depth and data size)     |
| **Hardware Needs**               | Can run on CPU                                | Needs GPU/TPU for efficient training              |
| **Interpretability**             | More interpretable (e.g., Decision Trees)     | Less interpretable (Black-box models)             |
| **Performance on Complex Tasks** | Limited                                       | Excels in tasks like vision, speech, NLP          |

---

### In Summary:

* **ML** = good for structured data and simpler tasks.
* **DL** = best for unstructured data like images, audio, and text where learning deep hierarchical features is essential.

### ✅ What Are Activation Functions?

**Activation functions** are mathematical operations applied to the output of a neuron. They decide **whether a neuron should “fire” or not**, and introduce **non-linearity** into neural networks — allowing them to **learn complex patterns** beyond linear relationships.

---

### 🧠 Why Activation Functions Matter

1. **Non-Linearity**
   Without activation functions, neural networks would behave like a simple linear model regardless of depth.

2. **Decision Making**
   They control how much signal should pass to the next layer.

3. **Helps in Convergence**
   Different activation functions help in faster and more stable training.

---

### 🔢 Common Activation Functions

---

#### 1. **Step Function**

* Used in perceptrons.
* Output:

  $$
  f(x) = 
  \begin{cases}
    1 & \text{if } x \geq 0 \\
    0 & \text{if } x < 0
  \end{cases}
  $$
* ❌ **Problem**: Not differentiable → not suitable for backpropagation.

---

#### 2. **Sigmoid Function**

* Formula:

  $$
  f(x) = \frac{1}{1 + e^{-x}}
  $$
* Output: (0, 1)
* ✅ Good for probabilities
* ❌ **Vanishing gradient problem** when $x$ is large/small.

---

#### 3. **Tanh (Hyperbolic Tangent)**

* Formula:

  $$
  f(x) = \frac{e^x - e^{-x}}{e^x + e^{-x}}
  $$
* Output: (-1, 1)
* ✅ Zero-centered
* ❌ Still suffers from vanishing gradients

---

#### 4. **ReLU (Rectified Linear Unit)**

* Formula:

  $$
  f(x) = \max(0, x)
  $$
* ✅ Most widely used due to simplicity and efficiency
* ✅ Avoids vanishing gradient (for positive values)
* ❌ **Dying ReLU**: Neurons can “die” if inputs are always negative

---

#### 5. **Leaky ReLU**

* Formula:

  $$
  f(x) = 
  \begin{cases}
    x & \text{if } x > 0 \\
    \alpha x & \text{if } x \leq 0 \ (\alpha \approx 0.01)
  \end{cases}
  $$
* ✅ Fixes Dying ReLU by allowing a small slope for negative inputs.

---

#### 6. **Parametric ReLU (PReLU)**

* Like Leaky ReLU but $\alpha$ is learned during training.
* ✅ Adaptive and more flexible

---

#### 7. **ELU (Exponential Linear Unit)**

* Formula:

  $$
  f(x) = 
  \begin{cases}
    x & \text{if } x \geq 0 \\
    \alpha (e^x - 1) & \text{if } x < 0
  \end{cases}
  $$
* ✅ Smooth output, better learning for negative inputs

---

#### 8. **Softmax**

* Converts a vector of raw scores into probabilities.
* Formula:

  $$
  \text{Softmax}(x_i) = \frac{e^{x_i}}{\sum_{j=1}^{n} e^{x_j}}
  $$
* ✅ Used in **output layers of multi-class classification**

---

### 🟨 Summary Table

| Activation Function | Output Range | Use Case                     | Issues                     |
| ------------------- | ------------ | ---------------------------- | -------------------------- |
| Step                | {0, 1}       | Perceptrons                  | Not differentiable         |
| Sigmoid             | (0, 1)       | Binary classification        | Vanishing gradients        |
| Tanh                | (-1, 1)      | Hidden layers                | Vanishing gradients        |
| ReLU                | \[0, ∞)      | Most hidden layers           | Dying neurons              |
| Leaky ReLU          | (-∞, ∞)      | Fix for ReLU                 | Small gradient in negative |
| PReLU               | (-∞, ∞)      | Learnable leaky slope        | Slightly complex           |
| ELU                 | (-α, ∞)      | Better for noisy data        | Slightly slower            |
| Softmax             | (0, 1) sum=1 | Output layer for multi-class | Not for hidden layers      |

### Importing The Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.19.0'

## Part - 1 : Data Preprocessing 

### Importing the Dataset

In [3]:
df = pd.read_csv('../datasets/Churn_Modelling.csv')
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1


In [4]:
X = df.iloc[: , 3:-1].values
y = df.iloc[:, -1].values
print(X)
print('\n')
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


[1 0 1 ... 1 1 0]


### Encoding the Categorical Data

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [6]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into training and test set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
print(X_train)
print('\n')
print(X_test)
print('\n')
print(y_train)
print('\n')
print(y_test)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


[0 0 0 ... 0 0 1]


[0 1 0 ... 0 0 0]


### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part - 2 : Building ANN

In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
ann = Sequential([
    Dense(units = 6, activation = 'relu'),
    Dense(units = 6, activation = 'relu'),
    Dense(units = 1, activation = 'sigmoid')
])


### Compiling the ANN

In [14]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [15]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7303 - loss: 0.5719 
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7952 - loss: 0.4694 
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7992 - loss: 0.4401 
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4120 
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4100 
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8130 - loss: 0.3930 
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8147 - loss: 0.3951 
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8208 - loss: 0.3806 
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8282 - loss: 0.3772 
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8292 - loss: 0.3742 
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8410 - loss: 0.3761 
Epoch 12/100
250/250 ━━━━━━━━━

## Part 4 - Making the predictions and evaluating the model

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [16]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
[[False]]


### Predicting the Test set results

In [17]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1517   78]
 [ 198  207]]


0.862